name: OWASP ZAP Integration with GitHub Actions

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the web application to scan'
        required: true
        default: 'http://testphp.vulnweb.com/'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Check Docker Version
        run: docker --version

      - name: List Docker Images
        run: docker images

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ github.event.inputs.target_url }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Check ZAP Logs
        run: cat zap.out
        if: failure()
